#!/usr/bin/env python3
"""
Simple test of kokoro-onnx based on official examples
"""
import soundfile as sf
from pathlib import Path
from kokoro_onnx import Kokoro

# Model paths
SERVER_ROOT = Path(__file__).resolve().parent
model_path = SERVER_ROOT / "models" / "kokoro" / "kokoro-v1.0.onnx"
voices_path = SERVER_ROOT / "models" / "kokoro" / "voices-v1.0.bin"

print(f"Model path: {model_path}")
print(f"Model exists: {model_path.exists()}")
print(f"Voices path: {voices_path}")
print(f"Voices exists: {voices_path.exists()}")

if not model_path.exists() or not voices_path.exists():
    print("❌ Model files not found!")
    exit(1)

print("\n🔧 Initializing Kokoro...")
kokoro = Kokoro(str(model_path), str(voices_path))
print("✅ Kokoro initialized")

print("\n🎤 Generating audio...")
# Use lang="en-us" as in official examples, not "en"
samples, sample_rate = kokoro.create(
    "Hello. This audio generated by kokoro!",
    voice="af_sarah",
    speed=1.0,
    lang="en-us"  # NOTE: Using "en-us" not "en"
)
print(f"✅ Audio generated: {len(samples)} samples at {sample_rate} Hz")

# Save to file
output_path = "/tmp/test_kokoro.wav"
sf.write(output_path, samples, sample_rate)
print(f"✅ Saved to {output_path}")
print(f"\n🔊 Play with: afplay {output_path}")
